2020-11-06 17:25:49,672 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 17:25:57,536 INFO __main__ VS-bigbase ball_within_template 0 -1 || loading models...
2020-11-06 17:25:57,688 INFO __main__ VS-bigbase ball_within_template 0 || getting auccess...
2020-11-06 17:26:09,290 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 17:41:10,532 INFO root Loading cache from /media/compute/homes/aharter/.cache/phyre/offline_simulation/100000/ball
2020-11-06 17:41:18,440 INFO __main__ VS-bigbase ball_cross_template 0 -1 || loading models...
2020-11-06 17:41:18,442 ERROR __main__ Exception occured:
Traceback (most recent call last):
  File "solver.py", line 230, in <module>
    solver.load_models(setup=eval_setup, fold=fold_id, no_second_stage=no_scnd_stage, load_from=load_from)
  File "/media/compute/homes/aharter/isy2020/phyre/flownet.py", line 2762, in load_models
    self.models[model].load_state_dict(T.load(load_path+f'/{model}.pt', map_location=T.device(device)))
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/media/compute/homes/aharter/miniconda3/envs/phyre/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saves/flownet/VS-bigbase_cross_0_-1/tar_net.pt'
